package com.shaishab316.englishstudy.subclass

import com.shaishab316.englishstudy.activity.Sub
import com.shaishab316.englishstudy.root

class CompletingStory : Sub() {
    override fun loadData() {
        add("King Midas And The Golden Touch")
        add("The King Lear And His Three Daughter")
        add("Sheikh Saadi")
        add("A thirsty crow")
        add("The Reward of an Honest Rickshaw Puller")
        add("The Scholar and the Boatman")
        add("Necessity of Gathering Practical Knowledge")
        add("Who Will Bell The Cat")
        add("Happiness Lies In Contentment")
        add("Selfless Help Has Its Reward")
        add("Law is Equal for All")
        add("Sense of Responsibility of a Boy")
        add("The Pied Piper of Hamelin")
        add("Lazy Grasshopper and Industrious Ant")
        add("The Wit of the Fox")
        add("A Dutiful Station Master")
        add("Issa Khan’s Greatness")
        add("The wooden Horse of Troy")
        add("Ready Wit of a Cook")
        add("Promised Should Be Kept")
        add("Nobility of Saladin")
        add("A Dutiful and Faithful Dog")
        add("Nobility Of A Landlord")
        add("A little learning is a dangerous thing")
        add("Rumour Results in Tragedy")
        add("The Clever Arab")
        add("The Cats and the Monkey")
        add("Think before you leap")
        add("The Value of Truthfulness")
        add("Look Before You Leap")
        add("A Rotten Apple Spoils the Good Ones")
        add("Three honest friends")
        add("The Cock Befools the Jackal")
        add("Rustam and His Brave Son")
        add("An Idiotic Thief’s Plight")
        add("Nobody believes a liar")
        add("An Old Farmer And His Sons")
        add("Dress Does Not Make A Man Great")
        add("Regular study")
        add("A Clever Astrologer")
        add("Might is Right")
        add("Slow and Steady Wins the Race")
        add("Tit for Tat")
        add("A Challenging Race")
        add("What is Sport to One May be Death to Another")
        add("Never tell a lie")
        add("A Lion And A Mouse")
        add("Importance of trees")
        add("Bayazid's Love for his Mother")
        add("A Friend in Need is a Friend Indeed")
        add("Black will take no other hue")
        add("Alexander, the Great Hero")
        add("Lame excuse")
        add("The Idle Sons")
        add("Three Knaves Fool a Brahmin")
        add("An Untoward Incident")
        add("Teaching of Prophet on Begging")
        add("The Wise Boy Who Saved Many Lives")
        add("Judgment of King Solomon")
        add("Truth Prevails Everywhere")
        add("Failure is the pillar of Success")
        add("A king and a astrologer")
        add("As You Sow, So Shall You Reap")
        add("Mohsin and a Thief")
        add("Titumir, the Great Freedom Fighter")
        add("A Greedy Dog Lost Everything")
        add("Honesty is The Best Policy")
        add("Pretending Beggar Gets Caught")
        add("Help each other in danger")
        add("Intelligent Crow Gets a Snake Killed")
        add("A Wise King")
        add("Help A Man While He Is in Danger")
        add("The King Regained His Kingdom")
        add("A tiny creature is important")
        add("Greed Brings Misery")
        add("Hojja and a Beggar")
        add("Unity is Strength")
        add("An Act of Bravery")
        add("Danger comes any time")
        add("Misers Are Never Happy")
        add("The Six Fools")
        add("The Rescue of a Child")
        add("The Old Farmer and His Quarrelsome Sons")
        add("A Foolish Crow and Sly Jackal")
        add("Self employment is better than unemployment")
        add("An honest wood cutter")
        add("Money Does Not Bring Happiness")
        add("Don't trust a liar")
        add("The Foolish Crow and A Sly Jackal")
        add("Narrow Escape From Death")
        add("Lack of Tolerance Causes Death and Destruction")
        add("Wicked Ass Learns a Lesson")
        add("The Honest Man")
        add("Presence of Mind")
        add("Be Kind to Everyone")
        add("The Virtuous Boy")
        add("The Generosity of Caliph Omar")
        add("The Ungrateful Snake")
        add("The Cunning Fox and the Stupid Crow")
        add("Necessity of Physical Labor")
        add("Grasp All, Lose All")
        add("Prudence of a Judge")
        add("The result of greed")
        add("Grapes are sour")
        add("A brave boy")
        add("An act of generosity")
        add("A fox without a tail")
    }

    override fun url() = "$root/Writing part/${title()}/"
    override fun title() = "Completing a Story"
}