package com.shaishab316.englishstudy.subclass

import com.shaishab316.englishstudy.activity.Sub
import com.shaishab316.englishstudy.root

class Letter : Sub() {
    override fun loadData() {
        add("Write a letter to your friend inviting him-her to your birthday party")
        add("Write a letter to your father informing him about your preparation for the ensuring examination")
        add("Write A Letter To Your Friend Telling Him-Her What Your Intern To Do After The S.S.C Examination")
        add("Write a Letter to Your Friend Describing How You Are Staying and Enjoying in Your Village Home")
        add("Write a Letter to Your Friend Describing Your Recent Visit to a Place of Historical Interest")
        add("Write a letter to your friend with a set of instructions on how to use the internet")
        add("Write a letter to your friend to attend you birthday")
        add("Write a letter to your friend describing your hobby")
        add("Write a letter to your friend about your family")
        add("Write a letter to your friend about annual sports day of your school")
        add("Write a letter to your friend describing your daily routine a Typical day of your life")
        add("Write a letter to your friend describing your experience of a train journey")
        add("Write a letter to your friend congratulating him on his brilliant result")
        add("Write a letter to your friend inviting him to the marriage ceremony of your elder sister")
        add("Write a letter to your friend describing your aim in life")
        add("Write a letter to your friend describing a street accident")
        add("Write a letter to your friend telling about how your school deferrers from his")
        add("Write a letter to your friend thanking him for his hospitality")
        add("Write a Letter to Your Friend About the Importance of Reading Newspaper")
        add("Write a letter to your younger brother about the usefulness of reading newspaper")
        add("Write a letter to your friend describing the bad effects of smoking")
        add("Write a letter to your friend telling him what you intend to do after your S.S.C examination")
        add("A letter to your friend congratulation on him-her on his-her brilliant success in the S S C examination")
        add("Write a letter to your friend describing how you celebrated pahela Baishakh")
        add("To The Editor Of Newspaper About Smoking Among The Students")
        add("To Editor Of A Newspaper Complaining About The Unplanned Road Digging All Over City")
        add("To The Editor Of A Newspaper Complaining About The Law And Order Situation In Your City")
        add("To Editor Of A Newspaper Complaining About Use Of Fire Crackers Thoughts The Year")
        add("To Editor Of A Newspaper Complaining About Increasing Use Of Narcotics In The Youth")
        add("To The Editor Of Newspaper About The Problems Created By The Beggars In The Busy Streets")
        add("To Your Uncle Seeking His Advice About What You Should Be After Passing The High School Examination")
        add("To Your Father Asking Permission To Join The Cadet Of Your School")
        add("To Your Brother Advising Him To Improve His Handwriting")
        add("To Your Brother Advising Him To Be Careful About His Health")
        add("To Your Brother About The Importance Of The Study Of Science Subjects")
        add("To Head Boy Of School Congratulating Him On His Success In Elected To Office Of General Secretary")
        add("To The Editor Of A Newspaper About The Problems Faced By The Commuters In City")
        add("To thanks for giving a wrist watch as birthday present")
        add("Write A Letter To Your Friend Describing The Experience Of The Flight")
        add("Write A Letter To Your Friend About The Importance Of Communicative English")
        add("Write A Letter To Your Friend Accepting His or Her Invitation")
        add("Write A Letter To Your Friend Declining His or Her Invitation")
        add("Write A Letter To Your Friend Consoling Him or Her For His or Her Failure In The Examination")
        add("Write A Letter Of Condolence Consoling Your Bereaved Friend Who Has Recently Lost His or Her Father or Mother")
        add("Write A Letter To Your Friend Expressing Your Sympathy For His or Her Illness")
        add("Write A Letter To Your Friend Describing A Street Accident You Have Witnessed")
        add("Write A Letter To Your Friend Describing A Picnic You Have Enjoyed")
        add("Write A Letter To Your Father Informing Him Of Your Performance In The Last Examination")
        add("Write A Letter To Your Younger Brother or Sister Advising Him or Her To Pay More Attention To Studies")
        add("To Your Father Asking Him To Send Some Money For Buying Books")
        add("Write A Letter To Your Pen-friend Who Wants Know About Your English Examination")
        add("Write A Letter To Your Friend, Giving Him-Her A Description Of An Unforgettable Incident In Your Life")
        add("Write A Letter To Your Friend In Describing Your Visit To A Fair")
        add("On Your Teacher Expressing Your Gratitude")
        add("Write A Letter To Your Uncle Thanking Him For The Birthday Gift")
        add("On Brother Introducing A Friend To Him")
        add("To Owner Of The House")
        add("On Friend Persuading Him To Take Part In Games")
        add("Friend Who Has Recently Lost His Mother")
        add("On Your Uncle Thanking Him For A Gift")
        add("On Brother Giving Advice How He Should Behave In The College")
        add("On Your Mother Asking For Money")
        add("On Friend Asking For The Loan Of Money")
        add("On Friend Who Has Suffered A Severe Pecuniary Loss")
        add("On An Order For Stationery To A Firm")
        add("On Behalf Of Your Principal To A Firm")
        add("On A Friend On His Birthday")
        add("Of Condolence To Your Friend")
        add("On Brother Letting Him About Various Problems Facing In City")
        add("On Complaint About Loss Of A Parcel To Railway Authorities")
        add("On Chairman Of The District Board")
        add("On Business Firm To A Customer")
        add("On Editor Of A Newspaper About Frequent Breakdown Of Electricity")
        add("On Expressing Your Concern About Friend’s Health")
        add("To Editor About The Pollution Created By A Smoke-emitting Factory")
        add("To A Newspaper About The Growing Noise Pollution")
        add("To A Leading Newspaper About The Problem Of Beggary In Town")
        add("To A Friend On His Birthday Expressing Good Wishes")
        add("To A Newspaper Complaining About Load Shedding Of Electricity")
        add("To A Business Firm Complain That Goods Were Received In Damaged Condition")
        add("Of Congratulation For Securing A-1 Grade In Examination")
        add("Letter To The Editor Of Some Newspaper Regarding Mismanagement In The Civil Hospital Of Your Town")
        add("From Lady Gives Tuition Asking Her About The Charges")
        add("From Old Teacher Thanking For The Special Care He Devoted During School Days")
        add("From Father To Son Enquiring About The Choice Of Profession In Life")
        add("To The Billing Department About Wrong Billing")
        add("To The Client In Reply To Complaint Receipt Of Articles In Damaged")
    }

    override fun url() = "$root/Writing part/${title()}/"
    override fun title() = "Letter"
}