package com.shaishab316.englishstudy.subclass

import com.shaishab316.englishstudy.activity.Sub
import com.shaishab316.englishstudy.root

class Paragraph : Sub() {
    override fun loadData() {
        add("A book fair")
        add("A Bus Stand")
        add("A College Canteen")
        add("A computer")
        add("A cyclone")
        add("A day labour")
        add("A Garment Worker")
        add("A Hartal Day")
        add("A Moonlit Night")
        add("A Railway Station")
        add("A rainy day")
        add("A Rickshaw Puller")
        add("A School library")
        add("A School Magazine")
        add("A stormy night")
        add("A Street Accident")
        add("A Street Hawker")
        add("A Winter Morning")
        add("Adolescence")
        add("An Ideal student")
        add("Arsenic")
        add("Bangabandhu Satellite")
        add("Bangladesh police")
        add("Bangladeshi Society")
        add("Basic Human Rights")
        add("Begum Rokeya")
        add("Climate Change")
        add("COVID-19")
        add("Deforestation")
        add("Diaspora")
        add("Digital Bangladesh")
        add("Dowry System")
        add("Early marriage")
        add("Earthquake")
        add("Environment Pollution")
        add("Facebook")
        add("Food Adulteration")
        add("Global love day")
        add("Global Village")
        add("Globalisation")
        add("Healthy Food")
        add("Independence Day")
        add("Internet")
        add("Liberation War")
        add("Load Shedding")
        add("Love")
        add("Mobile Phone")
        add("Mother Teresa")
        add("My First Day at College")
        add("My firstday in school")
        add("My Lockdown Days")
        add("Natural Calamities of Bangladesh")
        add("Online Class")
        add("Our National Flag")
        add("Our School")
        add("Padma Bridge")
        add("Paharpur")
        add("Pahela Baishakh")
        add("Premature Marriage")
        add("Price hike")
        add("Quarantine")
        add("River Gypsy")
        add("Rohingya Crisis in Bangladesh")
        add("Satellite TV Channels")
        add("Sidor")
        add("Student Life")
        add("Summer in Bangladesh")
        add("Terrorism")
        add("The 21st February")
        add("The Hakaluki Haor")
        add("The historical 7th March Speech")
        add("Traffic Jam")
        add("Traveling")
        add("Tree Plantation")
        add("Water Pollution")
        add("Women's Contribution to Society")
    }

    override fun url() = "$root/Writing part/${title()}/"
    override fun title() = "Paragraph"
}